import MouseMoveEffect from "@/components/Mouse_move_effect";
import "./globals.css";
import AppFooter from "@/components/nav/AppFooter";
import AppNavbar from "@/components/nav/AppNavbar";
import useSWR, { SWRConfig } from "swr";

export const metadata = {
  title: "Bm Rating",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased relative `}>
        <MouseMoveEffect />

        <AppNavbar />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
